config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "welcome/index"
  # route where any visitor require the helloWorldJob to be triggered
  post "welcome/trigger_job"

  # where visitor are redirected once job has been called
  get "other/job_done"

  resources :events, :categories

  namespace "api" do
    resources :events
    resources :categories
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events, dependent: :restrict_with_error

  validates :name, presence: true

  def self.permitted_attributes
    [ :name ]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category

  validates :name, presence: true

  def self.permitted_attributes
    [ :id, :category_id, :name, :observation, :timestamp ]
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::API
end

app/controllers/api/categories_controller.rb
class Api::CategoriesController < Api::BaseController
  def index
    render json: Category.all
  end

  def show
    render json: Category.find(params["id"])
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  def create
    category = Category.new(category_params)
    if category.save
      render json: category
    else
      render json: category.errors, status: :unprocessable_entity
    end
  end

  def update
    category = Category.find(params["id"])
    if category.update(category_params)
      render json: category
    else
      render json: category.errors, status: :unprocessable_entity
    end
  end

  def destroy
    category = Category.find(params["id"])
    if category.destroy
      render json: category
    else
      render json: category.errors, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  private

  def category_params
    params.fetch(:category, {}).permit(Category.permitted_attributes)
  end
end

app/controllers/api/events_controller.rb
class Api::EventsController < Api::BaseController
  def index
    render json: Event.all
  end

  def show
    render json: Event.find(params["id"])
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  def create
    event = Event.new(event_params)
    if event.save
      render json: event
    else
      render json: event.errors, status: :unprocessable_entity
    end
  end

  def update
    event = Event.find(params["id"])
    if event.update(event_params)
      render json: event
    else
      render json: event.errors, status: :unprocessable_entity
    end
  end

  def destroy
    event = Event.find(params["id"])
    if event.destroy
      render json: event
    else
      render json: event.errors, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound => e
    render json: { error: e.message }, status: :not_found
  end

  private

  def event_params
    params.fetch(:event, {}).permit(Event.permitted_attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.fetch(:category, {}).permit(Category.permitted_attributes)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @categories = Category.all
  end

  # GET /events/1/edit
  def edit
    @categories = Category.all
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(Event.permitted_attributes)
    end
end

app/controllers/other_controller.rb
# inside app/controllers/other_controller.rb
class OtherController < ApplicationController
  def job_done
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def trigger_job
    HelloJob.perform_later
    redirect_to other_job_done_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>
Name: <%= category.name %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "categories" %>

<h1>categories</h1>

<div id="categories">
  <ul>
    <% @categories.each do |category| %>
      <li><%= render category %></li>
      <p>
        <%= link_to "Show this category", category %>
      </p>
    <% end %>
  </ul>
</div>

<%= link_to "New category", new_category_path %>
<%= link_to "Events", events_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
</div>

Name: <%= event.name %>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :category %>
    <%= form.select :category_id, @categories.map { |c| [c.name, c.id] } %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Events" %>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>
<%= link_to "New category", new_category_path %>

app/views/events/new.html.erb
<% content_for :title, "New event" %>

<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Sidekiqtraining" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/other/job_done.html.erb
<!-- inside app/views/other/job_done.html.erb -->
<h1>Job was called</h1>

app/views/welcome/index.html.erb
<%# inside app/views/welcome/index.html.erb %>
<h1>This is h1 title</h1>

<%= form_with url: welcome_trigger_job_path do |f| %>
 <%= f.submit 'Launch job' %>
<% end %>

<%= link_to 'Events', events_path %>
<%= link_to 'Categories', categories_path %>